name: Integration tests

on:
  pull_request:

jobs:
  coverage:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sdk
        uses: actions/checkout@v3
        with:
          path: 'sdk'
      - name: Checkout nitro
        uses: actions/checkout@v3
        with:
          repository: OffchainLabs/nitro
          submodules: 'recursive'
          path: 'nitro'
      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: |
          cd sdk
          yarn
          yarn build
      - name: Start background nitro test-node.bash
        run: |
          cd nitro
          ./test-node.bash --init --no-blockscout &
      - name: Wait for nitro startup
        run: |
          cd sdk
          ./waitForNitro.sh
      - name: Copy .env
        run: |
          cd sdk
          cp ./.env-sample ./.env
      - name: Generate network file
        run: |
          cd sdk
          yarn gen:network
      - name: Integration tests
        run: |
          cd sdk
          yarn test:integration